# Generated by Django 4.0 on 2021-12-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yname', models.CharField(default='', max_length=20)),
                ('yemail', models.CharField(default='', max_length=20)),
                ('pnum', models.CharField(default='', max_length=20)),
                ('person', models.CharField(default='', max_length=20)),
                ('date', models.CharField(default='', max_length=20)),
                ('yevent', models.CharField(default='', max_length=20)),
                ('location', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
