# Generated by Django 4.0 on 2021-12-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_details_beer_details_none_details_nonveg_details_veg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='beer',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='none',
            new_name='foods',
        ),
        migrations.RemoveField(
            model_name='details',
            name='nonveg',
        ),
        migrations.RemoveField(
            model_name='details',
            name='veg',
        ),
        migrations.RemoveField(
            model_name='details',
            name='whisky',
        ),
        migrations.RemoveField(
            model_name='details',
            name='wine',
        ),
    ]
